package smarthome.client.presentation

const val RC_SIGN_IN = 9120
const val NEW_SCRIPT_GUID = 0L

const val ACTION_READ_CONTROLLER = "Read Controller"

const val SHOW_BOTTOM_BAR = "show_bottom_bar"
const val SHOW_TOOL_BAR = "show_tool_bar"

const val CONDITION_CONTAINER_CONTROLLER = "CONDITION_CONTAINER_CONTROLLER"
const val ACTION_CONTAINER_CONTROLLER = "ACTION_CONTAINER_CONTROLLER"
const val CONDITION_CONTAINER_VIEWMODEL = "CONDITION_CONTAINER_VIEWMODEL"
const val ACTION_CONTAINER_VIEWMODEL = "ACTION_CONTAINER_VIEWMODEL"