name: Android CI

on: 
  pull_request:
  push:
    branches:
        - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Mock google services json 
        run: |
          mkdir -p ignored/private_smarthome/services_json/smarthome.client
          mkdir -p ignored/private_smarthome/services_json/smarthome.library.datalibrary
          mkdir -p ignored/private_smarthome/services_json/smarthome.raspberry
          
          cp ./helpers/mock-google-services.json ignored/private_smarthome/services_json/smarthome.client/google-services.json
          cp ./helpers/mock-google-services.json ignored/private_smarthome/services_json/smarthome.library.datalibrary/google-services.json
          cp ./helpers/mock-google-services.json ignored/private_smarthome/services_json/smarthome.raspberry/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: true # Allow steps to continue even with test failures

      - name: Report
        uses: asadmansr/android-test-report-action@master
